# Reseaux de neurone


In [77]:
import numpy as np
from Module import ModuleLineaire, FASigmoide, MSELoss
from utils import load_usps, display_image, filter_values
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
X = [[1,2,-1,1,2]]

nn = ModuleLineaire(5, 1)
nn.forward(np.array(X[0]))
nn._gradient

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [2]:
all_train_X, all_train_Y = load_usps('USPS/USPS_train.txt')
train_X,train_Y = filter_values(all_train_X,all_train_Y, 0, 1)

all_test_X, all_test_Y = load_usps('USPS/USPS_test.txt')
test_X,test_Y = filter_values(all_test_X,all_test_Y, 0, 1)

array([ 1.,  0.])

In [127]:
pixels = 16*16
hiddenlayer_size = 16
output_size = 2
gradient_step = 0.1

batch_size = 16

loss = MSELoss()
activation = FASigmoide()
module1 = ModuleLineaire(pixels, hiddenlayer_size)
module2 = ModuleLineaire(hiddenlayer_size,output_size)
module3 = ModuleLineaire(output_size, output_size)

for i in range(train_X.shape[0]):
    x = train_X[i]
    y = train_Y[i]
    #Forward pour obtenir l'erreur
    a0 = x
    z1 = module1.forward(a0)
    a1 = activation.forward(z1)
    z2 = module2.forward(a1)
    a2 = activation.forward(z2)
    z3 = module3.forward(a2)
    a3 = activation.forward(z3)
    
    error = loss.backward(a3, y)
    print(error)
    #Backward
    delta3 = activation.backward_delta(error, z3)
    module3.backward_update_gradient(a2, delta3)
    
    delta2 = activation.backward_delta(module3.backward_delta(z2, delta3), z3)
    module2.backward_update_gradient(a1, delta2)
    
    delta1 = activation.backward_delta(module2.backward_delta(z1, delta2), z2)
    module1.backward_update_gradient(a0, delta1)
    
    if i % batch_size == 0:
        module1.update_parameters(gradient_step)
        module2.update_parameters(gradient_step)
        module3.update_parameters(gradient_step)
        module1.zero_grad()
        module2.zero_grad()
        module3.zero_grad()
    

[-0.84796243  0.42521264]
input : (2, 1)
delta : (2, 1)
(2, 2)
(2, 2)
------
input : (16, 1)
delta : (4, 1)
(16, 2)
(16, 4)
------


ValueError: operands could not be broadcast together with shapes (16,2) (16,4) (16,2) 

In [37]:
x = train_X[0]
y = train_Y[0]
#Forward pour obtenir l'erreur
tmp = activation.forward(input_module.forward(x))
tmp = activation.forward(hidden_module.forward(tmp))
result = activation.forward(output_module.forward(tmp))
error = loss.forward(result, y)
error

0.48808346610824815

In [118]:
delta = delta2
input = a2
delta = delta.reshape(-1,1)
input = input.reshape(-1,1)
np.dot(delta, input.T).T.shape

(16, 4)

In [123]:
delta2

array([[ 0.,  0.],
       [ 0.,  0.]])